modLoader = "kotlinforforge"
loaderVersion = "[0,)"
issueTrackerURL = "${mod_issues}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "${icon}"



[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinmcui"
mandatory = true
versionRange = "[${kotlinmcui_version},2.0.0)"
ordering = "NONE"
side = "CLIENT"
